# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.8.1'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'Xamarin.Forms.sln'
    feedsToUse: 'select'

# - task: VSBuild@1
#   inputs:
#     solution: 'Xamarin.Forms.sln'
#     vsVersion: '16.0'
- task: PowerShell@2
  inputs:
    filePath: 'build.ps1'
    arguments: '-Target NugetPack -ScriptArgs ''--packageVersion="5.0.0.1938-angpysha"'''
    errorActionPreference: 'silentlyContinue'
    pwsh: true
